spring.application.name=readit
server.port=${PORT:8080}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.redirect-uri=${KAKAO_OAUTH_REDIRECT_URL}
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.kakao.issuer-uri=https://kauth.kakao.com
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.kakao.scope=openid,account_email
logging.level.root=INFO
api.data4library.key=${LIBRARY_API_KEY}
spring.mvc.hiddenmethod.filter.enabled=true
spring.cache.cache-names=book
spring.cache.caffeine.spec=maximumSize=500
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.forward-headers-strategy=framework
logging.level.org.springframework.security=DEBUG